<?php

namespace Kulka\OxLearn\Controller;

use OxidEsales\Eshop\Application\Controller\FrontendController;
use OxidEsales\Eshop\Application\Model\Article;

class KulkaRandomArticle extends FrontendController
{
    protected $_sThisTemplate = 'kulka_random_article.tpl';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function render()
    {
        $randomArticle = oxNew(Article::class);
        $randomArticle->kulka_loadRandomArticle();
        var_dump('test');exit;

        $result = parent::render(); // TODO: Change the autogenerated stub

        return $this->_sThisTemplate;
    }
}
